### ISSUE TITLE
Cannot run UserAdminApp + SignInApp

### ISSUE THREAD

**Issue by warpech** [Polyjuice/UserAdmin#1]
Current version of UserAdminApp fails to start with SignInApp (Starcounter 2.0.3077.3) with an error:

> Trying to add a delegate to an already existing handler!

Below screenshot of the error message.

![useradminapp-exception](https://cloud.githubusercontent.com/assets/566463/6553850/7d557628-c655-11e4-9554-283152200897.png)

cc @alemoi, @andwah

**Comment by miyconst** [comment]
@warpech is this issue still relevant? UserAdmin + SignIn and/or GoogleSignIn works fine for me.

**Comment by warpech** [comment]
It was fixed by @alemoi. Closing
