### ISSUE TITLE
UserAdmin does not work

### ISSUE THREAD

**Issue by warpech** [Polyjuice/UserAdmin#5]
The app seems to not be working at the moment. 

@miyconst could you rework it in the similar way you reworked SignIn app?

**Comment by miyconst** [comment]
The app works, but it requires some permissions access the pages. Those permissions are not granted to new users created by GoogleSignIn.

Should I still rework the UserAmin app?
Should GoogleSignIn give these permissions by default?

**Comment by warpech** [comment]
1) GoogleSignIn should give appropriate permissions if it creates the `admin` user
2) In case of lacking permissions, UserAdmin should show an error message, not redirect to the home page

**Comment by miyconst** [comment]
1. Done.
2. Done.
3. Already in such state.
